#ifndef SERVER_CONSTANTS
#define SERVER_CONSTANTS


#define INITIAL_PROMPT "Welcome!\nWho are you?\n1. Customer\t2. Employee\t3. Manager\t4. Admin\nPress any other number to exit\nEnter the number corresponding to the choice!"

// ========== COMMON TEXT =============================

#define MANAGER_LOGIN_SUCCESS "Welcome!"
#define MANAGER_LOGOUT "Logging out!$"
#define MANAGER_MENU "1. Activate Customer\n2. Deactivate Customer Account\n3. Get loan details\n4. Assign Loan Processes\n5. Review Customer Feedback\n6. Change Password\nPress any other key to logout"
#define EMPLOYEE_LOGIN_SUCCESS "Welcome dear employee!"
#define EMPLOYEE_MENU "1. Add new account\n2. Modify Customer Details\n3. Process loan application\n4. View Assigned Loan Application\n5. Change Password\nPress any other key to logout"
// LOGIN
#define LOGIN_ID "Enter your login ID"
#define PASSWORD "Enter your password \n# "
#define INVALID_LOGIN "The login ID specified doesn't exist!$"
#define INVALID_PASSWORD "The password specified doesn't match!$"
#define SALT_BAE "666"

// GET ACCOUNT DETAILS
#define GET_ACCOUNT_NUMBER "Enter the account number of the account you're searching for"
#define GET_CUSTOMER_ID "Enter the customer ID of the customer you're searching for"

#define ERRON_INPUT_FOR_NUMBER "It seems you have passed a sequence of alphabets when a number was expected or you have entered an invalid number!\nYou'll now be redirected to the main menu!^"

#define INVALID_MENU_CHOICE "It seems you've made an invalid menu choice\nYou'll now be redirected to the main menu!^"

#define CUSTOMER_ID_DOESNT_EXIT "No customer could be found for the given ID"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIT "No customer could be found for the given login ID$"

#define EMPLOYEE_ID_DOESNT_EXIT "No employee could be found for the given ID"
#define EMPLOYEE_LOGIN_ID_DOESNT_EXIT "No employee could be found for the given login ID$"

#define ACCOUNT_ID_DOESNT_EXIT "No account could be found for the given account number"

#define TRANSACTIONS_NOT_FOUND "No transactions were performed on this account by the customer!^"

// ====================================================

// ========== ADMIN SPECIFIC TEXT======================

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME "Welcome dear admin! \nEnter your credentials to unlock!"
#define ADMIN_LOGIN_SUCCESS "Welcome Admin!"
#define EMPLOYEE_LOGIN_WELCOME "Welcome dear employee! \nEnter your credentials to unlock!"
#define MANAGER_LOGIN_WELCOME "Welcome dear manager! \nEnter your credentials to unlock!"

// ADMIN MENU
#define ADMIN_MENU "1. Add new Bank Employee\n2. Modify Customer Details\n3. Modify Employee Details\n4. Manage user roles\n5. Change Password\nPress any other key to logout"

// ADD CUSTOMER
#define ADMIN_ADD_CUSTOMER_PRIMARY "Enter the details for the primary customer\n"
#define ADMIN_ADD_CUSTOMER_SECONDARY "Enter the details for the secondary customer\n"
#define ADMIN_ADD_CUSTOMER_NAME "What is the customer's name?"
#define ADMIN_ADD_CUSTOMER_GENDER "What is the customer's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_CUSTOMER_AGE "What is the customer's age?"
#define ADMIN_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is : "
#define AUTOGEN_PASSWORD "1234" // append to end of next string macro
#define ADMIN_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define ADMIN_ADD_CUSTOMER_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"

// ADD ACCOUNT
#define ADMIN_ADD_ACCOUNT_TYPE "What type of account is to be created? Enter 1 for regular account and 2 for joint account"
#define ADMIN_ADD_ACCOUNT_NUMBER "The newly created account's number is :"

// DELETE ACCOUNT
#define ADMIN_DEACT_ACCOUNT_NO "What is the account number of the account you want to deactivate?"
#define ADMIN_DEACT_ACCOUNT_SUCCESS "This account has been successfully deactivated\nRedirecting you to the main menu ...^"
#define ADMIN_DEACT_ACCOUNT_FAILURE "This account cannot be deactivated since it still has some money\nRedirecting you to the main menu ...^"

// MODIFY CUSTOMER INFO
#define ADMIN_MOD_CUSTOMER_ID "Enter the ID of the customer who's information you want to edit"
#define ADMIN_MOD_CUSTOMER_MENU "Which information would you like to modify?\n1. Name 2. Age 3. Gender \nPress any other key to cancel"
#define ADMIN_MOD_CUSTOMER_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_CUSTOMER_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_CUSTOMER_NEW_AGE "What's the updated value for age?"

#define ADMIN_MOD_CUSTOMER_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

#define ADMIN_LOGOUT "Logging you out now superman! Good bye!$"

// ====================================================

// ========== CUSTOMER SPECIFIC TEXT===================

// LOGIN WELCOME
#define CUSTOMER_LOGIN_WELCOME "Welcome dear customer! Enter your credentials to gain access to your account!"
#define CUSTOMER_LOGIN_SUCCESS "Welcome beloved customer!"

#define CUSTOMER_LOGOUT "Logging you out now dear customer! Good bye!$"
#define EMPLOYEE_LOGOUT "Logging you out now dear employee! Good bye!$"

// ADMIN MENU
#define CUSTOMER_MENU "1. View Account Balance\n2. Deposit Money\n3. Withdraw Money\n4. Transfer Funds\n5. Apply for a loan\n6. Add Feedback\n7. View Transaction History\n8. Change Password\nPress any other key to logout"

#define ACCOUNT_DEACTIVATED "It seems your account has been deactivated!^"

#define DEPOSIT_AMOUNT "How much is it that you want to add into your bank?"
#define DEPOSIT_AMOUNT_INVALID "You seem to have passed an invalid amount!^"
#define DEPOSIT_AMOUNT_SUCCESS "The specified amount has been successfully added to your bank account!^"

#define WITHDRAW_AMOUNT "How much is it that you want to withdraw from your bank?"
#define WITHDRAW_AMOUNT_INVALID "You seem to have either passed an invalid amount or you don't have enough money in your bank to withdraw the specified amount^"
#define WITHDRAW_AMOUNT_SUCCESS "The specified amount has been successfully withdrawn from your bank account!^"

#define PASSWORD_CHANGE_OLD_PASS "Enter your old password"
#define PASSWORD_CHANGE_OLD_PASS_INVALID "The entered password doesn't seem to match with the old password"
#define PASSWORD_CHANGE_NEW_PASS "Enter the new password"
#define PASSWORD_CHANGE_NEW_PASS_RE "Reenter the new password"
#define PASSWORD_CHANGE_NEW_PASS_INVALID "The new password and the reentered passwords don't seem to pass!^"
#define PASSWORD_CHANGE_SUCCESS "Password successfully changed!^"

// ====================================================


#define ACCOUNT_FILE "./records/account.bank"
#define CUSTOMER_FILE "./records/customer.bank"
#define TRANSACTION_FILE "./records/transactions.bank"
#define EMPLOYEE_FILE "./records/employee.bank"
#define FEEDBACK_FILE "./records/feedback.txt"
#define LOAN_FILE "./records/loan.bank"
#define ADMIN_FILE "./records/admin.bank"


#define ADMIN_ADD_EMPLOYEE_NAME "What's the employee name"
#define ADMIN_ADD_EMPLOYEE_GENDER "What's the employee gender"
#define ADMIN_ADD_EMPLOYEE_WRONG_GENDER "The gender provided is wrong choice"
#define ADMIN_ADD_EMPLOYEE_AGE "What's the employee age"
#define ADMIN_ADD_EMPLOYEE_AUTOGEN_LOGIN "The autogenerated login ID for the employee is :"
#define ADMIN_ADD_EMPLOYEE_AUTOGEN_PASSWORD "The autogenerated password for the employee is :"

#define ADMIN_MOD_EMPLOYEE_ID "Enter the ID of the employee who's information you want to edit"
#define ADMIN_MOD_EMPLOYEE_MENU "Which information would you like to modify?\n1. Name 2. Age 3. Gender \nPress any other key to cancel"
#define ADMIN_MOD_EMPLOYEE_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_EMPLOYEE_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_EMPLOYEE_NEW_AGE "What's the updated value for age?"

#define ADMIN_MOD_EMPLOYEE_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

#define ADMIN_ACT_ACCOUNT_NO "What is the account number of the account you want to activate?"
#define ADMIN_ACT_ACCOUNT_SUCCESS "This account has been successfully activated\nRedirecting you to the main menu ...^"

#define TRANSFER_FUND_AMOUNT "What is the amount you want transfer?"
#define TRANSFER_FUND_ACCOUNT "What is the account number of account in which you want to tranfer the funds?"

#define LOAN_AMOUNT "Enter the amount of loan you want to apply"
#define LOAN_ID "The loan is applied with loan id:"

#define LOAN_NOT_FOUND "There is no loan applied by customer"
#define LOAN_NOT_ASSIGNED "There is no loan assigned to you"

#define GET_LOAN_ID "Enter the loan id of the loan you want to assign"
#define GET_EMP_ID "Enter the employee id of the employee you want to assign the loan"
#define LOAN_ID_DOESNT_EXIT "The loan id provided does not exist"
#define LOAN_AMOUNT_INVALID "The loan amount is invalid"
#define PROCESS_LOAN_ID "Enter the loan id you want to process"

#endif